twig:
    default_path: '%kernel.project_dir%/templates'

    globals:
        pictures_public_directory: 'img/'
        avatar_public_directory: 'img/'

when@test:
    twig:
        strict_variables: true
